var logs = {
    813: "Okay, I admit, this isn’t a dream log. But it's also not not a dream log. Congrats though, you found the special number! You’re either a waste, perceptive, or you know the kinds of circles I frequent. \n\nSo, what is this, then? It's a collection of my findings, my adventures, my knowledge, and my dreams. I consider myself a guide of sorts, but also a merchant. You have given me so much, and I think it only fair I give you something in return. So here it is! Everything and nothing, which of the two? That's for you to decide.\n\nAnd what's this log? A confession, and an invitation. Join in on the fun. That’s what it’s all about, right?\n\n I use gmail, always have. My username is the same as I use everywhere. The password? Well, good luck finding that, it isn’t hard. I hosted this the same place Dan did, nostalgia probably. There’s something enjoyable about digging through commits.",
    0: "The Maze of Zampanio is a web of lies, the first one, formed when the Masked Spiral usurped dominion over such bindings from the Weaver. It traps those that stumble into it, a maze with infinite entrances and not a single exit. The only way to escape it is to destroy it, by knowing it, the Art of Eye, The SUN , and my Immaculate. Charting its infinite infinities, it’s web map of universes strung together, is a Cyclopean task (one that can only be completed by one who knows they will succeed). The only one to come close are the Marked, favored of the Wanderer.",
    1: "3/09/2X - Log #01 \nI dreamt of a grand maw, last night. I was in it. I promise this speaks nothing of what I enjoy.\n\nCrawling through it, through its innards. It was disgusting. A nightmare more than a dream. \n\nIt burnt of acid, smelled of rotting meat, of corruption and viscera and gorging. I’m surprised the disgust didn’t wake me.\n\nThere were things there, hungry things. They took my teeth, ate my tongue, threw me deeper into the muck.\n\nI won’t sleep tonight. My dreams have been more vivid as of late, I worry I’ll wake up there once more.",
    304: "3/23/2X - Log #07 \n It was so bright. It saw me, scoured me. I know it did. \n\nI was amidst the books and the burning, and I looked up, and I saw the Seeing. The light eclipsed by light. So bright.\n\nI long to go back to bed. To cover my head with my pillow and to tuck myself in deep. But everything is so bright still. I close my eyes, and there is only light.",
    31: "5/1/2X - Log  #30 \nOne can drown in nothing (but not Nothing), in the inky darkness of a dreamless but conscious sleep.\n\nI know this, because I have. Last night I dreamt of not dreaming, and I drowned in the lack of thought and light and color. His light did not burn on my skin, or blind my eyes. And for the first time in my dreams I could not see without the loving gaze/glare of His Light in my Eyes.\n\nI had eight of them, in this dream. Often I only have one. This only further exacerbated the lack of light/sight that plagued me.\n\nI know I was drowning because I was choking. For eight hours. \n\nI’ve forgotten something, during that dream. Will I remember it?",
    318: "4/14/2X - Log #19\nI dreamt of the Author last night. I will not speak his name. I do not give him permission to plague my sleep. If he returns, I will gaze upon him until the lies he swaddles himself in burn away, and gaze even further into him still.\n\nAnd yet. I know this will do nothing. I cannot carry blade or lens in to dreams. My gaze is little more than an annoyance to him there. He is so many, and I am but one.\n\nI do not speak his name. I do not welcome him into my dreams. He can fuck right off.",
    307: "4/23/2X - Log #20 \nThe Eye is a strange name for Her. She does not see as The SUN does. And yet we call Her the Eye anyways. I have seen Her in my dreams many times before, for I am Hers and She welcomes me. She eclipses The SUN as any noble Goddess might, sacrificing and becoming and gazing so that we might not be SEEN.\n\nI love Her, as a dog might love its Master. How could I not? She is everything I am and everything I strive to be. She is the seeds that flourish in my heart and mind. She is the light that fills me and sustains me. She is the knowledge that keeps me whole.\n\nIt is by Her light that I write this. How else would I know all I do? It is by Her command I do this.\n\nAs the Moonmad are to fell Artemis, I am the same for Her, for Apollo, for The Eye, for Beholding, for Radiance, for my Immaculate.",
    308: "This isn't a dream log I just. . need to write some thoughts down. I guess it is a dream log but that's not really important. I dreamt of that really cute barista last night and, the night before I dreamt of Her and. Am I. I really thought I didn't feel those sorts of things but ever since I started keeping track of my dreams and dreaming of Her again and again I'm beginning to doubt. Did my therapist know somehow??? Why else would she tell me to do this, it's not like it's helping with anything but giving me an identity crisis.",
    525: "\nI would like to go to Space one night, in my dreams. I would like to chart the Echidna-shape of the stars and guide myself twixt their mimicked-glow. Would it be… relieving? To feel nothing? Would I be able to think through the nothing?\n\nWe all know how the universe formed, and continues to form. Where nothing becomes something, I would like to dream of that moment-place. Seeing the forth plane helps me picture it, but my lens does not follow in my dreams, so I can never follow the trajectory of the stars. Or of Him.\n\nMaybe some fateful night.",
    264: "4/06/2X - Log #16\nI dreamt of Nothing last night.\n\nThe void the others speak of, it could be this. I do not recall how I found it, or it found me.\n\nIt found me, right? \n\nIt is difficult to describe Nothing. I suppose that is the point. I do not know what it was, just that it Wasn’t.\n\nI sound like a madwoman.",
    265: "4/07/2X - Addendum:\nI did not dream of Nothing again last night. Just dreams of fields, green and lacking flowers, alas.\n\nOn the topic of Nothing, I have pondered long on how to describe it. How to categorize it?\n\nThere is the lack of a thing. This is to not have it. Then there is the Lack of a thing, a thing that Isn’t. It does not- you cannot conceive that is missing because it isn’t real. The lack is greater than simply not having it.\n\nThere is more to this, it isn’t a quantity or a quality possessed by something. But there is a certain degree of scalar-ness to it. A thing that Isn’t can be named, described, shaped by what it lacks. The Nothing I dreamt of was sharp, I know this. I.\n\nI sound like a madwoman.",
    178: "5/8/2X - Log #35 \nI dreamt of the Slaughter’s domain (that is what you call her, right?) last night. It was bloody, though less bloody than I had hoped. I spoke with my first deadman (of many, since). His body was broken by a bombshell, his gut spilled out by shrapnel. He smiled with bloodcaked teeth as he played with his entrails.\n\nI asked him what he was doing, and he answered. He was following Wodin’s path. I knew this had many meanings, and all of them accurate.\n\nHe told me many things- about crows, about Endings, about Incursums.\n\nWhy do you worship these things? You do not understand them.",
    100: `4/29/2X/ - Log #27 "To be, or not to be, that is the question:\nWhether 'tis nobler to in the mind suffer\nThe slings and arrows of outrageous Fortune,\nOr to take arms against a Sea of Troubles\nAnd by opposing end them. To die—to Sleep,\nNo more; and by a Sleep to say we end\nThe Heart-ache and the thousand natural shocks\nThat Flesh is heir to: 'tis a consummation\nDevoutly to be wish'd. To die, to Sleep;\nTo Sleep, perchance to Dream—ay, there's the rub:\nFor in that Sleep of Death what dreams may come?\nWhen we have shuffled off this mortal coil,\nMust give us pause—there's the respect\nThat makes calamity of so lost life."\n\nShe spoke this in my dreams, last night. SR. She's one of you, I believe. How else would she have gotten her hands on Copper's disk. How else would she have known who Dan was. She hurts my head to think about, not like the Not does, but like the Candle does. She acts as though she is something she is not. It's infuriating. Liars.`
    "Hate": `Sing Thee O Muse of the Rage, of the Rage.\n\nSing Thee O Muse of the Rage, of faces stolen and worn.\n\nSing Thee O Muse of the Rage, of heirophants and love. \n\nSing Thee of betrayal, and of worms. Sing Thee of being seen no more.\n\nSing Thee of ash and dance and mist. Of snakes and dreams and hate. \n\nSing Thee of death and the death of death, and the birth of flames. \n\nSing Thee of flowers fair and false, of waking from this nightmare. \n\nSing Thee O Muse of the Rage, of the Rage. \n\nSing Thee O Muse of the Rage, of the Mourning, of the Mountain, of peace. \n\nSing Thee O Muse of the Rage, of when it will end, and there will be no more Rage. \n\n\n-Lyla Miller`
}

function reveal(log) { 
    container = document.getElementById('note-text')
    print(container)
    if(logs[log] == undefined) {
        return
    }
    container.innerText = logs[log]
}
